export default function Terms() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pt-8 pb-24">
        <div className="text-center py-12">
          <h1 className="text-4xl font-extrabold text-slate-900 mb-4">Terms of Service</h1>
          <p className="text-slate-500">Last updated: June 1, 2024</p>
        </div>
        <div className="space-y-8 text-slate-600 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using PilotStaff, you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">2. Description of Service</h2>
            <p>PilotStaff provides AI-powered tools and virtual AI staff members for business use. Our services include but are not limited to content creation, SEO analysis, and automated business tasks.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">3. User Accounts</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">4. Payment Terms</h2>
            <p>Paid subscriptions are billed monthly via PayPal. You may cancel at any time from your dashboard. Refunds are issued at our discretion for unused time.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">5. Acceptable Use</h2>
            <p>You agree not to use our services for illegal purposes, to generate harmful content, or to violate any applicable laws or regulations.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">6. Intellectual Property</h2>
            <p>Content generated by our AI tools is owned by you. PilotStaff retains rights to the underlying technology and platform.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">7. Limitation of Liability</h2>
            <p>PilotStaff is not liable for any indirect, incidental, or consequential damages arising from your use of our services.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">8. Contact</h2>
            <p>For questions about these terms, contact us at legal@pilotstaff.com.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
